### ISSUE TITLE
Try this

### ISSUE THREAD

**Issue by bassemhelal18** [Yonn1981/Repo#1]
اهلا بك صديقي قم بتجربه هذا التعديل اعتقد انه افضل resolver
ملف hoster في lib ![image](https://user-images.githubusercontent.com/77381611/223994424-eceaeace-ed10-4498-9453-d7a2d9c3e841.jpeg)
و هذا في ملف الsettings 
![image](https://user-images.githubusercontent.com/77381611/223994619-b52cd221-53e4-4bca-84ba-1027bcbb5ece.jpeg)![image](https://user-images.githubusercontent.com/77381611/223994672-14d8e4a5-6121-4b50-a7ae-4ac5d0417e55.jpeg) و قم بتفعيل ال resolver في الsettings

**Comment by bassemhelal18** [comment]
تغير urlresolver الي resolveurl

**Comment by Yonn1981** [comment]
اهلا بك...
سأجرب ما تقول ... شكرا جزيلا على المساعدة

**Comment by bassemhelal18** [comment]
Small letter
resolveurl not ResolveURL goodluck

**Comment by Yonn1981** [comment]
> Small letter resolveurl not ResolveURL goodluck

تمام اشتغل .. لكن ما ممبزات استخدامه مادام الاضافة تقدر تفتح الروابط بدون تفعيلها في الاعدادت؟

**Comment by bassemhelal18** [comment]
الاضافه تقدر تفتح بس ده بيكون عليه مواقع اكتر ومحدث باستمرار و الموقع الذي تريد اضافته يمكنك ان ترسل اللينك الي https://github.com/Gujal00/ResolveURL و سيتم اضافته 
و ايضا الكود القديم خطا

**Comment by Yonn1981** [comment]
شيء طيب ، كيف اخليه مفعل افتراضيًا بدل تفعيله بالـالsettings؟

وماذا قصدت بالكود القديم خطا؟

**Comment by bassemhelal18** [comment]
الكود القديم كان يستخدم https://github.com/t0mm0/xbmc-urlresolver

**Comment by Yonn1981** [comment]
شكرا لك ـ
