### ISSUE TITLE
موقع أفلام الوقت

### ISSUE THREAD

**Issue by Yanish96** [Yonn1981/Repo#10]
السلام عليكم 
الموقع العربي وقت الأفلام هو الذي ينقص ماتريكس فهو يضع محتواه الخاص ولا يضع محتوى من مواقع اخرى لو أمكن إضافته و شكرا
https://movtime3.store/home5/

**Comment by Yonn1981** [comment]
وعليكم السلام ورحمة الله وبركاته

ان شاء الله سأضيفه في اقرب وقت ...

**Comment by Yonn1981** [comment]
تم
