### ISSUE TITLE
add host 

### ISSUE THREAD

**Issue by Haithameng84** [Yonn1981/Repo#14]
ممكن اضافة هذا الهوست لان عدلت عليه ولم افلح بالتكمله بدون زحمه 
https://www.mediafire.com/file/t0cto9lwk4mv1h4/veo.tar.gz/file

**Comment by Yonn1981** [comment]
لا استطيع الوصول للموقع .. للمساعدة احتاج source كل صفحة (صفحة الافلام ، صفحة المسلسلات والحلقات وصفحة المشاهدة ..)

اعمل لي HAR لكل الموقع وارسله لي، الطريقة:
https://www.youtube.com/watch?v=m98WFEXbhIs

اتاكد انك عامل Preserve log . ادخل صفحة الافلام - اختر فلم - ادخل صفحة المشاهدة - اختر سيرفر للمشاهدة - بعدين اعمل ملف ال HAR

وان شاء الله اقدر اساعد ولكم لا اضمن
