### ISSUE TITLE
Add a new Host

### ISSUE THREAD

**Issue by Medarc3** [Yonn1981/Repo#19]
السلام عليكم ، ممكن إضافة هذا الموقع nunflix.com موقع رائع و به سيرفرات local يمكنك أن تلقي نظر عليه و إضافته إن كان ممكن و شكرا على كل المجهودات 🤗

**Comment by Yonn1981** [comment]
وعليكم السلام ورحمة الله وبركاته ،

ألقيت نظرة على الموقع ، وحسب رأيي الموقع لا يوفر سيرفرات local بمعنى local .. انما يستخدم "كود" لجلب الروابط من مجموعة مواقع ويعرض سيرفراتها .. وبناءا عليه بعض الروابط بدون ترجمة ...

عندي في الاضافة مواقع انجليزية توفر بعض هذه الروابط ..

هل في الموقع مثلا افلام او مسلسلات لا تتوفر في مواقع الاضافة الحالية؟

**Comment by Medarc3** [comment]
شكرا على الرد أخي يونس ، بالتوفيق 😊🤗
