### ISSUE TITLE
مشكل في موقع فاصل 

### ISSUE THREAD

**Issue by Medarc3** [Yonn1981/Repo#20]
السلام عليكم اخي يونس لو ممكن إصلاح موقع فاصل و تخطي الحماية المظافة على الموقع و شكرا جزيلا 🤗😊

**Comment by Yonn1981** [comment]
وعليكم السلام ورحمة الله وبركاته 
لم اجد حماية على الموقع 🤔 ... يعمل عندي بدون مشاكل  ...

اذا كنت تستخدم vpn او بروكسي حاول اغلاقه..

**Comment by Medarc3** [comment]
لا استخدم لا vpn ولا بروكسي .. ربما مشكل آخر عندي ، شكرا أخي يونس 🥰

**Comment by Yonn1981** [comment]
احيانا يكون الـ DNS هو سبب المشكلة..

**Comment by Medarc3** [comment]
شكرا أخي العزيز 😊

**Comment by Yonn1981** [comment]
ارسلت التحديث 6.4.0n ..
جرب في الاعدادات استخدام scrappey لتجاوز الحماية (قمت بالتجربة وتم تجاوز الحماية) سيكون بطيئا ولكن فعال

على فكرة هناك الكثير من المواقع البديلة في الاضافة توفر جودة ممتازة.

**Comment by Medarc3** [comment]
شكرا جزيلا اخي العزيز 😊🤗
