### ISSUE TITLE
كيف يمكن اضافة repository 

### ISSUE THREAD

**Issue by fyritp** [Yonn1981/Repo#21]
السلام عليكم كيف يمكن زيادة الاضافة الخاصة بك بعد تنصيب اضافة ماتريكس في كودي ؟

**Comment by Yonn1981** [comment]
وعليكم السلام ورحمة الله وبركاته 
لم افهم السؤال .. 

هل تقصد عنوان المستودع (repository) لكودي الخاص بي؟ 

هو:
https://yonn1981.github.io

**Comment by fyritp** [comment]
نعم شكرا جزيلا قمت بتنصيبه لكن الملاحظ ان هناك بطئ شديد في البحث عن المسلسلات في اي موقع ثم بعد الدخول لاي حلقة تنتظر اكثر من 5 دقائق لتحميلها وبعض المرات لا تريد التحميل هل هذا عادي ؟

**Comment by fyritp** [comment]
هل يمكن ان يكون المشكل من احد dependencies ؟ لانني قمت بتنصيب بعضها يدويا عن طريق تحميل zip الخاص بها، وبعضها لم استطع تنصيبها مثل 
Plugin.video.torrest
Githu addon repository 
Cloud drive common module
Python-dateutil
هل احد هذه يمكن ان يؤثر على سرعة البحث؟

**Comment by Yonn1981** [comment]
المفروض الاضافة تركب بدون تدخل يدوي .. 

نعم بعض الاضافات اختيارية (optional) ولا تأثر .. لكن اذا تعذر تركيب الاضافة لنقص في الـ dependencies فلربما انك لم تفعل في اعدادات كودي التحميل من اي مستودع وليس الرسمي فقط..

جربت الاضافة في اي جهاز؟ 

ملاحظة:
الـ Github Addon Repository يتم تحميلها من المستودع الخاص بي ومن خلالها تجد Plugin.video.torrest وهو خاص لتشغيل روابط التورنت (لكن تحتاج الى جهاز يملك مساحه كافة ومواصفات مقبولة) ولهذا هو اختياري

**Comment by fyritp** [comment]
شكرا بارك الله فيك تم حل المشكل عبر تفعيل التحميل من اي مستودع
بالنسبة لموقع فاصل عند الدخول لاي حلقة يظهر ؤسالة error cloudflare 
هل بسبب تطبيقهم لحماية cloudflare ؟ ام يجب علي تنصيب اضافة اخرى؟

**Comment by fyritp** [comment]
كيف يمكنني تغيير الاعدادات لاختيار scrapeninja؟ هل هي اضافة يجب تنصيبها؟

**Comment by fyritp** [comment]
لقد قمت بذلك لم يعد يظهر رسالة كلاودفلير لكن المحتوى الخاص بفاصل لا يظهر يعطي no information 
هل يمكنكم تعديل main url ليصبح faselhds.world
بدل faselhd.center ؟؟

**Comment by Yonn1981** [comment]
ارسلت التحديث 6.4.0n ..
جرب في الاعدادات استخدام scrappey لتجاوز الحماية (قمت بالتجربة وتم تجاوز الحماية) سيكون بطيئا ولكم فعال

- على فكرة هناك الكثير من المواقع البديلة في الاضافة توفر جودة ممتازة.

**Comment by fyritp** [comment]
شكرا تم الاشتغال كما قلت بطيء بعض الشيء 
هل يمكنك اعطائي مثال لموقع يوفر جودة FHD قمت بالبحث في كثير منهم لم اجد الا HD

**Comment by Yonn1981** [comment]
بالنسبة لي افضل استخدام المواقع الاجنبية مثل f movie و super show و the movie archive

**Comment by fyritp** [comment]
شكرا بارك الله فيك
