### ISSUE TITLE
Trakt integration login

### ISSUE THREAD

**Issue by fyritp** [Yonn1981/Repo#22]
السلام عليكم اعتذر عن الازعاج 
اذا امكن معرفة كيفية ربط حساب trakt باضافة matrix
وحدت فقط اعدادات trakt integration 
ولا وجود ل login

**Comment by Yonn1981** [comment]
وعليكم السلام ورحمة الله وبركاته 

اهلا ، تحصلهم في قائمة فيديواتي او My Videos ثم My Accounts ..

هناك تعمل ربط لحسابك..

**Comment by fyritp** [comment]
شكرا جزيلا وجدتها
