### ISSUE TITLE
Need help to pypass Cloudflare 

### ISSUE THREAD

**Issue by samirinhoo** [Yonn1981/Repo#24]
Currently I enabled the pypass settings on matrix to scrapyeninja . But host Faselhd doesn't display any information while selecting any caregory. Can you please have a look and provide any information to watch this site on your matrix. Thanx bro.

**Comment by Yonn1981** [comment]
Use scrappey..

**Comment by samirinhoo** [comment]
great thanx bro

**Comment by samirinhoo** [comment]
sorry but next page in series and movies categories is not displaying, only one page , can you check plez

**Comment by Yonn1981** [comment]
commit 362d566 fixed it hopefully.. Update the addon..

**Comment by samirinhoo** [comment]
Thanx for updates. Next page working ok now
