### ISSUE TITLE
تغيير موقع Animeblkom

### ISSUE THREAD

**Issue by fyritp** [Yonn1981/Repo#25]
السلام عليكم 
هل يمكنكم تغيير رابط موقع animeblkom
إلى هذا الرابط 
https://animeblkom.net
لأن الرابط السابق لم يعد يشتغل في اضافة matrix حتى مع تشغيل cloudflare bypass 
وشكرا بارك الله فيك

**Comment by Yonn1981** [comment]
وعليكم السلام ورحمة الله وبركاته
الرابط نفسه هو في الاضافة ولكن الموقع فعل الحماية ..

جربت استخدام scrappey ونجح في فك الحماية عندي !

**Comment by fyritp** [comment]
جربت ولم يشتغل هل يجب تفعيل خيار 
Use cloudflare on search?

**Comment by Yonn1981** [comment]
> جربت ولم يشتغل هل يجب تفعيل خيار Use cloudflare on search?

هذا الخيار لتفعيل فك الحماية للمواقع اثناء البحث العام (لا انصح بتفعيلة اذا كان لديك الكثير من المواقع المحجوبة لانه سيأخذ وقت طويييل)

ايضا الموقع جربته اكثر من مرة وشغال عندي فلا أستطيع مساعدتك اكثر من ذلك ... يمكنك استخدام مواقع الانمي الاخرى في الاضافة!
