### ISSUE TITLE
Add scrappey

### ISSUE THREAD

**Issue by sy-oe** [Yonn1981/Repo#27]
السلام عليكم
أخي الكريم، أولاً الشكر لك على مجهودك الكبير في ماتريكس
قرأت أنك تنصح باستخدام scrappey في الاعدادات ، بحثت بكل الاعدادات وبحثت على قوقل 3 ساعات ولم أتوصل الى معرفة طريقة تفعيلها واستخدامها، هل يمكنك المساعدة بوضع صورة لكيفية تفعيلها
الكثير من المواقع/الروابط تفتح على الكمبيوتر وبدون vpn وبنفس الوقت لا تعمل من خلال كودي/ماتريكس ولا اعلم السبب وحتى مع تشغيل vpn لا تعمل معظم الروابط
لم يتبقى الا عدد قليل من المواقع تعمل روابطها في ماتريكس رغم أن هذه المواقع نصفها يفتح طبيعي بدون vpn هنا في السعودية
ارجو منك المساعدة وشكرا
ملاحظة: اعضاء المنتدى ينتظرونك لمساعدتهم
https://www.tunisia-sat.com/forums/threads/3939280/page-180

**Comment by Yonn1981** [comment]
وعليكم السلام ورحمة الله وبركاته ،
بالنسبة لـ scrappey ، تجدها في اعدادات الاضافة (غير من flaresolver):
Sources - > Cloud-flare Bypass -> scrappey 

بطيئة ولكن بالنسبة لي تفي بالغرض. 

المواقع التي تعمل لديك بالمتصفح ، هل هي محمية بالـ cloudf-lare ؟ ، اذا كانت محمية تحتاج تفعيل scrappey ، اما اذا لا فتأكد هل عنوان المواقع في الاضافة هو نفسه عنوان المواقع التي تعمل لديك؟

بالنسبة للمنتدى ، انا لست صاحب الاضافة الاصلي انا فقط اقوم بتعديلات خاصة بي وقد لا تناسب البعض وقد لا تعمل مع الغير.. لكن اي شخص يستطيع استخدام اضافتي المعدلة من الريبو الخاص بي:
`https://yonn1981.github.io`

ولك جزيل الشكر

**Comment by sy-oe** [comment]
شكرا لك
هل هي محمية بالـ cloudf-lare ؟ القليل من المواقع فقط
باقي المواقع تعمل طبيعي ولكنها لا تعمل على ماتريكس، والأخ صاحب الاضافة غير متواجد، هل لديك العلم متى يتم تحديث ماتريكس.
وشكرا

**Comment by Yonn1981** [comment]
لا علم لي ، تستطيع سؤال صاحب الاضافة الاخ زومبي ...

جرب تغيير الروابط بالاضافة بالروابط العاملة لديك..

**Comment by sy-oe** [comment]
لم أستطع معرفة من أين يمكنني تغيير الروابط بالإضافة
هل يمكنك المساعدة بالتوضيح
ولك الشكر والتقدير

**Comment by Yonn1981** [comment]
يعتمد على نظام التشغيل.. لكن بشكل عام تذهب لمجلد كودي وتدخل مجلد الاضافات (addons) وبعدين مجلد الاضافة.. تدخل resources ثم تفتح الملف sites.json


اذا الامر صعب عليك ، عطني اسماء المواقع وعنوان كل موقع لاقارن واجرب اعمل لك التغيير للتجربة..

**Comment by sy-oe** [comment]
شاكر لك مساعدتك
كودي 21  يعمل لدي على جهاز اندرويد tv box قديم ولم أجد اعدادات التي ذكرتها لي. ولكني فعلت scrappey باتباع خطواتك.
بالنسبة للمواقع فاستطعت تدقيق بعضها:
https://witanime.quest/
https://www.witanime.biz/
https://v.witanime.video/
https://animeblkom.net/
https://www.blkom.com/
https://cdn3.xsanime.live/
هذه في الأعلى لا تعمل بشكل كامل في الاضافة وبنفس الوقت تعمل المواقع طبيعي من الكمبيوتر، انمي بالكوم عليه حماية كلاود فلير.

https://web3.topcinema.fun/
https://www.fushaar.link/
بالنسبة ل فشار تعمل في الاضافة ويمكن رؤية قائمة الافلام والمسلسلات ولكن روابط المشاهدة لا يعمل منها شيء رغم الروابط تعمل من الكمبيوتر طبيعي. توب سينما نفس وضع فشار ولكن أحيانا يعمل رابط الجودة المتعددة ولكن لا تتغير الجودة وتبقى بجودة عالية.

https://web1.faselhd1watch.christmas/
فاصل اعلاني لم يعمل والان وانا اكتب لك اصبح يعمل، يمكنك النظر به.

موضوع اخر، بشكل عام هناك مشاكل بالبحث فلا يظهر الا بضعة مواقع رغم وجود الفيلم او المسلسل في مواقع تعمل ضمن الاضافة.
والنقطة الأخيرة..  هي روابط المشاهدة على ok معظمها لا يعمل في الاضافة ونعم أحيانا يعمل في موقع ما. ولكن على الكمبيوتر يعمل بشكل طبيعي في غالبية المواقع. ولم استخدم vpn من الكمبيوتر، ولم أشهد الا حماية كلاود من انمي بالكوم.
شكرا لك تعبك وجهدك.

**Comment by Yonn1981** [comment]
حسنا ، هناك بعض الامور تحتاج توضيح:
مواقع الاضافة مبينه هنا:
`https://github.com/Yonn1981/Repo/blob/master/repo/plugin.video.matrix/resources/sites.json`

1- موقع witanime:
رابط الموقع الاصلي هو: https://witanime.cyou

المواقع التي ذكرتها ليست روابط للموقع الاصلي وانما تقليد .. ماذا يحصل عند الدخول على الموقع الاصلي؟

2- موقع animeblkom:
الرابط هو https://animeblkom.net (محجوب ولكن يعمل مع scrappy) هل يعمل لديك هذا الرابط في المتصفح

3- موقع xsanime:
اضفت الرابط لموقع بديل (فعل الروابط البديلة في الاعدادات alternative links) .. يجب تحديث الاضافة لتاريخ اليوم

4- موقعي topcinma و fushaar:
لم اجد مشكلة في الروابط .. على كلٍ حال اضفت روابط التحميل مع المشاهدة لموقع topcinema

بالنسبة للبحث .. ياريت مثال عن فيلم او مسلسل مع كتابة ما تكتب بخانة البحث وما المواقع التي لم تظهر في النتائج

**Comment by sy-oe** [comment]
1- موقع witanime:
رابط الموقع الاصلي هو: https://witanime.cyou/

المواقع التي ذكرتها ليست روابط للموقع الاصلي وانما تقليد .. ماذا يحصل عند الدخول على الموقع الاصلي؟

نعم يدخل طبيعي من الكمبيوتر الى الموقع ويتغير الى https://witanime.quest ولا يعمل من الاضافة ويظهر لا يوجد معلومات
2- موقع animeblkom:
الرابط هو https://animeblkom.net/ (محجوب ولكن يعمل مع scrappy) هل يعمل لديك هذا الرابط في المتصفح

نعم يدخل طبيعي من الكمبيوتر الى الموقع ويبقى كما هو https://animeblkom.net ولكن عليه حماية كلاود فلير ولا يعمل من الاضافة ويظهر لا يوجد معلومات علماً بأن scrappy مفعلة 
3- موقع xsanime:
اضفت الرابط لموقع بديل (فعل الروابط البديلة في الاعدادات alternative links) .. يجب تحديث الاضافة لتاريخ اليوم
قمت بتفعيل خيار الروابط البديلة للمواقع من الاعدادات/المصدر ولا يوجد تحديث جديد للاضافة، عند دخول الى xsanime من الكمبيوتر يعمل بشكل طبيعي ومن الاضافة يظهر لا يوجد معلومات.
4- بالنسبة للبحث لاحقاً سأضع لك مثال مع البيانات التي طلبتها.

بشكل عام من من الغريب أن ثلاثة مواقع انمي تفتح من الكمبيوتر ولا تفتح من الاضافة، مما جلعني افتح متصفح كروم الموجود في جهاز (قديم) اندرويد tv box الذي عليه كودي 21 الجديد، وكانت المفاجئة لم يفتح أي من الثلاثة مواقع. جربت من جهازي الثاني شيلد انفيديا (ليس عليه كودي) وأيضاً لم تفتح الثلاثة مواقع. إني محتار مما يجري.

**Comment by sy-oe** [comment]
جربت اليوم حذف/تعديل DNS من الراوتر ولم تفتح الثلاث مواقع وتعمل طبيعي من الكمبيوتر
ملاحظة بخصوص animezid عند فتح المصدر من الاضافة تأتي 5 خيارات -خيارين للبحث -افلام كرتون -مسلسلات كرتون -مسلسلات انمي
الخيار الأخير يسبب تجمد كودي وتوقف الشاشة.

**Comment by Yonn1981** [comment]
اضفت https://witanime.quest كموقع بديل (تحديث تاريخ اليوم)

بالنسبة لـ animezid  -مسلسلات انمي ـ شغال ولكن عدد المسلسلات يفوق الـ 200 مسلسل في الصفحة ـ فاذا جهازك بطيء سيعلق ويأخذ وقت طويل

جربت animeblkom مرة اخرى ويعمل لدي (يتجاوز الحماية)


ربما المشكلة من مزود الانترنت لديك؟ جربت VPN؟ صراحة لا اعلم ، لا املك هذه المشاكل..

**Comment by sy-oe** [comment]
شكرا لك، سأقوم بالتحديث.
نعم أعتقد أن المشكلة من طرفي أو من مزود الخدمة جربت الكثير من الحلول ولم ينفع شيء بما فيها ستاتيك ip ،ونعم vpn يحل بعض المشاكل.
شكرا لك ولجهودك وبالتوفيق لك فقد أفدتني كثيرا
