### ISSUE TITLE
Help Enabel new Url resolver

### ISSUE THREAD

**Issue by samirinhoo** [Yonn1981/Repo#3]
Hi bro. please help me configure which settings in matrix dashborad to activate or to enable it to use latest URL resolver . i already installed the new script.module.resolveurl-5.1.98y

**Comment by samirinhoo** [comment]
i fu

**Comment by Yonn1981** [comment]
Hi, 
Yes, the script.module.resolveurl-5.1.98y testing update fixed sflix site links but break filemoon resolver (maybe others)... 

I'm just testing English sites.. you go back to original script.module.resolveurl-5.1.98 update at the moment (but only sflix site won't work..).

**Comment by Yonn1981** [comment]
تم رفع تحديث يحل المشكلة

**Comment by samirinhoo** [comment]
Ok I will test new updates.. mailnly Ask4movie ( filemoon)   and Cimaclub-drkvid link is the issue link that was not  resolved in previous version.

**Comment by Yonn1981** [comment]
تم رفع تحديث يحل مشكلة روابط cimaclub بدون استخدام resolveurl ...

**Comment by samirinhoo** [comment]
issues solved , thanx bro.
