### ISSUE TITLE
CF movies issue

### ISSUE THREAD

**Issue by samirinhoo** [Yonn1981/Repo#5]
Hi bro. Recently unfortunately Ask4movie is CF protected . Is there is any solution to sort out this issue?. Also I would like you to have a look on some English movies streaming site in future if you can add them . Thanx
- losmovies.ru
- gowatchseries.tv
- membed1.com

**Comment by Yonn1981** [comment]
للاسف الحل انك تستخدم FlareSolverr (في البيت مفعل FlareSolverr وعامل اللازم)

اضفت موقع membed لان كان سهل الاضافة ..

**Comment by samirinhoo** [comment]
Thanx for adding site. regarding FlareSolverr is it a plugin to be installed in Kodi or in my windows PC . Is it available in any repo for Kodi?

**Comment by Yonn1981** [comment]
FlareSolverr عبارة عن سيرفر 
الاضافة مبرمجة انها تستعين بهذا السيرفر في حال فشل بالاتصال بالموقع ، تجد في الاعدادات وضع رقم الـ ip الخاص بـ FlareSolverr وعادة يكون هو رقم الايبي للكمبيوتر او الابتوب او حتى raspberry pi المبرمج عليه FlareSolverr
