### ISSUE TITLE
please add this arabic site

### ISSUE THREAD

**Issue by samirinhoo** [Yonn1981/Repo#8]
Hi bro. , can you please add this site [shahid4u](https://shahhed4u.cam/)

**Comment by Yonn1981** [comment]
Hi,
I will see about it.. hope it is not difficult ... It is a duplicate? site of original but now closed shahid4u ..

**Comment by samirinhoo** [comment]
Hi bro. It isOriginal site and it's video links available in your plugin hosters.

**Comment by Yonn1981** [comment]
Ok added.. pls test

**Comment by samirinhoo** [comment]
Working ok . Thanx bro
