### ISSUE TITLE
 طلب إضافة موقع جديد

### ISSUE THREAD

**Issue by Medarc3** [Yonn1981/Repo#9]
المرجو إضافة هذا الموقع t.ifushaar.com/ موقع فشار ،فهو ليس موقع فشار الموجود في ماتريكس بل موقع مغاير لديه سيرفر متعدد الجودات ويحتوي على مكتبة ضخمة من الأفلام القديمة لم تكن موجودة إلا على إجي بيست الأصلي الذي أغلق ولن يعود و شكرا

**Comment by Yonn1981** [comment]
سألقي نظرة على الموقع واذا كان سهل الاضافة

**Comment by Yonn1981** [comment]
تمت اضافة الموقع

**Comment by Medarc3** [comment]
جزيل الشكر لك 🤗🥰
